<?php

namespace app\models;

use yii\base\Model;

class Files extends Model
{
    public $name;
    public $file;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function upload(){

    }
}

?>
